version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
