version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  run-tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm test

workflows:
  my-custom-workflow:
    jobs:
      - run-tests