name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
      
      - name: Run Tests
        run: |
          output=$(npm run test)
          echo "Output: $output"
          echo "MY_OUTPUT=$output" >> $GITHUB_ENV
      - name: Print Output
        run: |
          echo "Output: $MY_OUTPUT"
        env:
          MY_OUTPUT: ${{ env.MY_OUTPUT }}
